import { type MaybeFutureEither } from "../either/future/maybeFutureEither";
import { type MaybePromise, type EscapeVoid, type BreakGenericLink } from "./types";
import { type AnyValue } from "./types/anyValue";
type MaybePromiseLike<GenericValue extends unknown> = MaybePromise<GenericValue> | MaybeFutureEither<GenericValue>;
/**
 * The asyncInnerPipe() method builds a reusable asynchronous pipeline. It returns a function that accepts a value or a promise, runs each step while waiting for the previous one, then returns a promise of the final result.
 * 
 * Signature: `asyncInnerPipe(pipe1, pipe2)` → returns a value
 * 
 * The input value is not mutated.
 * 
 * ```ts
 * const input = [
 * 	{
 * 		host: "api.local",
 * 		retries: 1,
 * 	},
 * 	{
 * 		host: "api.external",
 * 		retries: 2,
 * 	},
 * ];
 * 
 * const result = await asyncPipe(
 * 	input,
 * 	A.map(
 * 		asyncInnerPipe(
 * 			({ host, retries }) => ({
 * 				url: `https://${host}/health`,
 * 				retries,
 * 			}),
 * 			// fake HTTP request
 * 			async({ url, retries }) => Promise.resolve({
 * 				url,
 * 				status: 200,
 * 				retries,
 * 			}),
 * 			({ status, url, retries }) => `${status} on ${url} (retries: ${retries})`,
 * 		),
 * 	),
 * );
 * // result: [
 * //    "result: "200 on https://api.local/health (retries: 1)",
 * //    "result: "200 on https://api.external/health (retries: 2)"
 * // ]
 * 
 * ```
 * 
 * @see https://utils.duplojs.dev/en/v1/api/common/asyncInnerPipe
 * 
 * @namespace C
 * 
 */
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe1>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe2>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid, GenericOutputPipe3 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromiseLike<GenericOutputPipe3>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe3>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid, GenericOutputPipe3 extends AnyValue | EscapeVoid, GenericOutputPipe4 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromiseLike<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromiseLike<GenericOutputPipe4>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe4>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid, GenericOutputPipe3 extends AnyValue | EscapeVoid, GenericOutputPipe4 extends AnyValue | EscapeVoid, GenericOutputPipe5 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromiseLike<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromiseLike<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromiseLike<GenericOutputPipe5>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe5>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid, GenericOutputPipe3 extends AnyValue | EscapeVoid, GenericOutputPipe4 extends AnyValue | EscapeVoid, GenericOutputPipe5 extends AnyValue | EscapeVoid, GenericOutputPipe6 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromiseLike<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromiseLike<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromiseLike<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromiseLike<GenericOutputPipe6>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe6>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid, GenericOutputPipe3 extends AnyValue | EscapeVoid, GenericOutputPipe4 extends AnyValue | EscapeVoid, GenericOutputPipe5 extends AnyValue | EscapeVoid, GenericOutputPipe6 extends AnyValue | EscapeVoid, GenericOutputPipe7 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromiseLike<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromiseLike<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromiseLike<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromiseLike<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromiseLike<GenericOutputPipe7>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe7>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid, GenericOutputPipe3 extends AnyValue | EscapeVoid, GenericOutputPipe4 extends AnyValue | EscapeVoid, GenericOutputPipe5 extends AnyValue | EscapeVoid, GenericOutputPipe6 extends AnyValue | EscapeVoid, GenericOutputPipe7 extends AnyValue | EscapeVoid, GenericOutputPipe8 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromiseLike<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromiseLike<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromiseLike<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromiseLike<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromiseLike<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromiseLike<GenericOutputPipe8>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe8>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid, GenericOutputPipe3 extends AnyValue | EscapeVoid, GenericOutputPipe4 extends AnyValue | EscapeVoid, GenericOutputPipe5 extends AnyValue | EscapeVoid, GenericOutputPipe6 extends AnyValue | EscapeVoid, GenericOutputPipe7 extends AnyValue | EscapeVoid, GenericOutputPipe8 extends AnyValue | EscapeVoid, GenericOutputPipe9 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromiseLike<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromiseLike<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromiseLike<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromiseLike<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromiseLike<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromiseLike<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromiseLike<GenericOutputPipe9>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe9>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid, GenericOutputPipe3 extends AnyValue | EscapeVoid, GenericOutputPipe4 extends AnyValue | EscapeVoid, GenericOutputPipe5 extends AnyValue | EscapeVoid, GenericOutputPipe6 extends AnyValue | EscapeVoid, GenericOutputPipe7 extends AnyValue | EscapeVoid, GenericOutputPipe8 extends AnyValue | EscapeVoid, GenericOutputPipe9 extends AnyValue | EscapeVoid, GenericOutputPipe10 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromiseLike<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromiseLike<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromiseLike<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromiseLike<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromiseLike<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromiseLike<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromiseLike<GenericOutputPipe9>, pipe10: (input: GenericOutputPipe9) => MaybePromiseLike<GenericOutputPipe10>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe10>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid, GenericOutputPipe3 extends AnyValue | EscapeVoid, GenericOutputPipe4 extends AnyValue | EscapeVoid, GenericOutputPipe5 extends AnyValue | EscapeVoid, GenericOutputPipe6 extends AnyValue | EscapeVoid, GenericOutputPipe7 extends AnyValue | EscapeVoid, GenericOutputPipe8 extends AnyValue | EscapeVoid, GenericOutputPipe9 extends AnyValue | EscapeVoid, GenericOutputPipe10 extends AnyValue | EscapeVoid, GenericOutputPipe11 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromiseLike<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromiseLike<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromiseLike<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromiseLike<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromiseLike<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromiseLike<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromiseLike<GenericOutputPipe9>, pipe10: (input: GenericOutputPipe9) => MaybePromiseLike<GenericOutputPipe10>, pipe11: (input: GenericOutputPipe10) => MaybePromiseLike<GenericOutputPipe11>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe11>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid, GenericOutputPipe3 extends AnyValue | EscapeVoid, GenericOutputPipe4 extends AnyValue | EscapeVoid, GenericOutputPipe5 extends AnyValue | EscapeVoid, GenericOutputPipe6 extends AnyValue | EscapeVoid, GenericOutputPipe7 extends AnyValue | EscapeVoid, GenericOutputPipe8 extends AnyValue | EscapeVoid, GenericOutputPipe9 extends AnyValue | EscapeVoid, GenericOutputPipe10 extends AnyValue | EscapeVoid, GenericOutputPipe11 extends AnyValue | EscapeVoid, GenericOutputPipe12 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromiseLike<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromiseLike<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromiseLike<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromiseLike<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromiseLike<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromiseLike<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromiseLike<GenericOutputPipe9>, pipe10: (input: GenericOutputPipe9) => MaybePromiseLike<GenericOutputPipe10>, pipe11: (input: GenericOutputPipe10) => MaybePromiseLike<GenericOutputPipe11>, pipe12: (input: GenericOutputPipe11) => MaybePromiseLike<GenericOutputPipe12>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe12>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid, GenericOutputPipe3 extends AnyValue | EscapeVoid, GenericOutputPipe4 extends AnyValue | EscapeVoid, GenericOutputPipe5 extends AnyValue | EscapeVoid, GenericOutputPipe6 extends AnyValue | EscapeVoid, GenericOutputPipe7 extends AnyValue | EscapeVoid, GenericOutputPipe8 extends AnyValue | EscapeVoid, GenericOutputPipe9 extends AnyValue | EscapeVoid, GenericOutputPipe10 extends AnyValue | EscapeVoid, GenericOutputPipe11 extends AnyValue | EscapeVoid, GenericOutputPipe12 extends AnyValue | EscapeVoid, GenericOutputPipe13 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromiseLike<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromiseLike<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromiseLike<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromiseLike<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromiseLike<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromiseLike<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromiseLike<GenericOutputPipe9>, pipe10: (input: GenericOutputPipe9) => MaybePromiseLike<GenericOutputPipe10>, pipe11: (input: GenericOutputPipe10) => MaybePromiseLike<GenericOutputPipe11>, pipe12: (input: GenericOutputPipe11) => MaybePromiseLike<GenericOutputPipe12>, pipe13: (input: GenericOutputPipe12) => MaybePromiseLike<GenericOutputPipe13>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe13>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid, GenericOutputPipe3 extends AnyValue | EscapeVoid, GenericOutputPipe4 extends AnyValue | EscapeVoid, GenericOutputPipe5 extends AnyValue | EscapeVoid, GenericOutputPipe6 extends AnyValue | EscapeVoid, GenericOutputPipe7 extends AnyValue | EscapeVoid, GenericOutputPipe8 extends AnyValue | EscapeVoid, GenericOutputPipe9 extends AnyValue | EscapeVoid, GenericOutputPipe10 extends AnyValue | EscapeVoid, GenericOutputPipe11 extends AnyValue | EscapeVoid, GenericOutputPipe12 extends AnyValue | EscapeVoid, GenericOutputPipe13 extends AnyValue | EscapeVoid, GenericOutputPipe14 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromiseLike<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromiseLike<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromiseLike<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromiseLike<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromiseLike<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromiseLike<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromiseLike<GenericOutputPipe9>, pipe10: (input: GenericOutputPipe9) => MaybePromiseLike<GenericOutputPipe10>, pipe11: (input: GenericOutputPipe10) => MaybePromiseLike<GenericOutputPipe11>, pipe12: (input: GenericOutputPipe11) => MaybePromiseLike<GenericOutputPipe12>, pipe13: (input: GenericOutputPipe12) => MaybePromiseLike<GenericOutputPipe13>, pipe14: (input: GenericOutputPipe13) => MaybePromiseLike<GenericOutputPipe14>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe14>>>;
export declare function asyncInnerPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue | EscapeVoid, GenericOutputPipe2 extends AnyValue | EscapeVoid, GenericOutputPipe3 extends AnyValue | EscapeVoid, GenericOutputPipe4 extends AnyValue | EscapeVoid, GenericOutputPipe5 extends AnyValue | EscapeVoid, GenericOutputPipe6 extends AnyValue | EscapeVoid, GenericOutputPipe7 extends AnyValue | EscapeVoid, GenericOutputPipe8 extends AnyValue | EscapeVoid, GenericOutputPipe9 extends AnyValue | EscapeVoid, GenericOutputPipe10 extends AnyValue | EscapeVoid, GenericOutputPipe11 extends AnyValue | EscapeVoid, GenericOutputPipe12 extends AnyValue | EscapeVoid, GenericOutputPipe13 extends AnyValue | EscapeVoid, GenericOutputPipe14 extends AnyValue | EscapeVoid, GenericOutputPipe15 extends AnyValue | EscapeVoid>(pipe1: (input: GenericInput) => MaybePromiseLike<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromiseLike<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromiseLike<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromiseLike<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromiseLike<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromiseLike<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromiseLike<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromiseLike<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromiseLike<GenericOutputPipe9>, pipe10: (input: GenericOutputPipe9) => MaybePromiseLike<GenericOutputPipe10>, pipe11: (input: GenericOutputPipe10) => MaybePromiseLike<GenericOutputPipe11>, pipe12: (input: GenericOutputPipe11) => MaybePromiseLike<GenericOutputPipe12>, pipe13: (input: GenericOutputPipe12) => MaybePromiseLike<GenericOutputPipe13>, pipe14: (input: GenericOutputPipe13) => MaybePromiseLike<GenericOutputPipe14>, pipe15: (input: GenericOutputPipe14) => MaybePromiseLike<GenericOutputPipe15>): (input: MaybePromiseLike<GenericInput>) => Promise<Awaited<BreakGenericLink<GenericOutputPipe15>>>;
export {};
