import { type MaybePromise, type BreakGenericLink } from "./types";
/**
 * The asyncInnerPipe() method builds a reusable asynchronous pipeline. It returns a function that accepts a value or a promise, runs each step while waiting for the previous one, then returns a promise of the final result.
 * 
 * Signature: `asyncInnerPipe(pipe1, pipe2)` → returns a value
 * 
 * The input value is not mutated.
 * 
 * ```ts
 * const input = [
 * 	{
 * 		host: "api.local",
 * 		retries: 1,
 * 	},
 * 	{
 * 		host: "api.external",
 * 		retries: 2,
 * 	},
 * ];
 * 
 * const result = await asyncPipe(
 * 	input,
 * 	A.map(
 * 		asyncInnerPipe(
 * 			({ host, retries }) => ({
 * 				url: `https://${host}/health`,
 * 				retries,
 * 			}),
 * 			// fake HTTP request
 * 			async({ url, retries }) => Promise.resolve({
 * 				url,
 * 				status: 200,
 * 				retries,
 * 			}),
 * 			({ status, url, retries }) => `${status} on ${url} (retries: ${retries})`,
 * 		),
 * 	),
 * );
 * // result: [
 * //    "result: "200 on https://api.local/health (retries: 1)",
 * //    "result: "200 on https://api.external/health (retries: 2)"
 * // ]
 * 
 * ```
 * 
 * @see https://utils.duplojs.dev/en/v1/api/common/asyncInnerPipe
 * 
 */
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe1>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe2>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromise<GenericOutputPipe3>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe3>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromise<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromise<GenericOutputPipe4>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe4>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromise<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromise<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromise<GenericOutputPipe5>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe5>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromise<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromise<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromise<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromise<GenericOutputPipe6>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe6>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromise<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromise<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromise<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromise<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromise<GenericOutputPipe7>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe7>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromise<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromise<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromise<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromise<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromise<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromise<GenericOutputPipe8>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe8>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromise<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromise<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromise<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromise<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromise<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromise<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromise<GenericOutputPipe9>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe9>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromise<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromise<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromise<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromise<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromise<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromise<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromise<GenericOutputPipe9>, pipe10: (input: GenericOutputPipe9) => MaybePromise<GenericOutputPipe10>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe10>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromise<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromise<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromise<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromise<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromise<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromise<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromise<GenericOutputPipe9>, pipe10: (input: GenericOutputPipe9) => MaybePromise<GenericOutputPipe10>, pipe11: (input: GenericOutputPipe10) => MaybePromise<GenericOutputPipe11>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe11>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown, const GenericOutputPipe12 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromise<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromise<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromise<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromise<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromise<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromise<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromise<GenericOutputPipe9>, pipe10: (input: GenericOutputPipe9) => MaybePromise<GenericOutputPipe10>, pipe11: (input: GenericOutputPipe10) => MaybePromise<GenericOutputPipe11>, pipe12: (input: GenericOutputPipe11) => MaybePromise<GenericOutputPipe12>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe12>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown, const GenericOutputPipe12 extends unknown, const GenericOutputPipe13 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromise<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromise<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromise<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromise<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromise<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromise<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromise<GenericOutputPipe9>, pipe10: (input: GenericOutputPipe9) => MaybePromise<GenericOutputPipe10>, pipe11: (input: GenericOutputPipe10) => MaybePromise<GenericOutputPipe11>, pipe12: (input: GenericOutputPipe11) => MaybePromise<GenericOutputPipe12>, pipe13: (input: GenericOutputPipe12) => MaybePromise<GenericOutputPipe13>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe13>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown, const GenericOutputPipe12 extends unknown, const GenericOutputPipe13 extends unknown, const GenericOutputPipe14 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromise<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromise<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromise<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromise<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromise<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromise<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromise<GenericOutputPipe9>, pipe10: (input: GenericOutputPipe9) => MaybePromise<GenericOutputPipe10>, pipe11: (input: GenericOutputPipe10) => MaybePromise<GenericOutputPipe11>, pipe12: (input: GenericOutputPipe11) => MaybePromise<GenericOutputPipe12>, pipe13: (input: GenericOutputPipe12) => MaybePromise<GenericOutputPipe13>, pipe14: (input: GenericOutputPipe13) => MaybePromise<GenericOutputPipe14>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe14>>;
export declare function asyncInnerPipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown, const GenericOutputPipe12 extends unknown, const GenericOutputPipe13 extends unknown, const GenericOutputPipe14 extends unknown, const GenericOutputPipe15 extends unknown>(pipe1: (input: GenericInput) => MaybePromise<GenericOutputPipe1>, pipe2: (input: GenericOutputPipe1) => MaybePromise<GenericOutputPipe2>, pipe3: (input: GenericOutputPipe2) => MaybePromise<GenericOutputPipe3>, pipe4: (input: GenericOutputPipe3) => MaybePromise<GenericOutputPipe4>, pipe5: (input: GenericOutputPipe4) => MaybePromise<GenericOutputPipe5>, pipe6: (input: GenericOutputPipe5) => MaybePromise<GenericOutputPipe6>, pipe7: (input: GenericOutputPipe6) => MaybePromise<GenericOutputPipe7>, pipe8: (input: GenericOutputPipe7) => MaybePromise<GenericOutputPipe8>, pipe9: (input: GenericOutputPipe8) => MaybePromise<GenericOutputPipe9>, pipe10: (input: GenericOutputPipe9) => MaybePromise<GenericOutputPipe10>, pipe11: (input: GenericOutputPipe10) => MaybePromise<GenericOutputPipe11>, pipe12: (input: GenericOutputPipe11) => MaybePromise<GenericOutputPipe12>, pipe13: (input: GenericOutputPipe12) => MaybePromise<GenericOutputPipe13>, pipe14: (input: GenericOutputPipe13) => MaybePromise<GenericOutputPipe14>, pipe15: (input: GenericOutputPipe14) => MaybePromise<GenericOutputPipe15>): (input: MaybePromise<GenericInput>) => Promise<BreakGenericLink<GenericOutputPipe15>>;
