import { type BreakGenericLink } from "./types";
/**
 * The pipe() method chains up to 15 synchronous functions, passing the output of one as the input of the next. It returns the last computed value and stays fully typed at each step.
 * 
 * Signature: `pipe(input, pipe1, pipe2)` → returns a value
 * 
 * The input value is not mutated.
 * 
 * ```ts
 * const input = {
 * 	price: 10,
 * 	quantity: 3,
 * };
 * const tvaRate = 1.2;
 * const digit = 2;
 * 
 * const result = pipe(
 * 	input,
 * 	({ price, quantity }) => price * quantity,
 * 	(value) => value * tvaRate,
 * 	(value) => `${value.toFixed(digit)}€`,
 * );
 * // result: "36€"
 * ```
 * 
 * @see https://utils.duplojs.dev/en/v1/api/common/pipe
 * 
 */
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1): BreakGenericLink<GenericOutputPipe1>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2): BreakGenericLink<GenericOutputPipe2>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2, pipe3: (input: GenericOutputPipe2) => GenericOutputPipe3): BreakGenericLink<GenericOutputPipe3>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2, pipe3: (input: GenericOutputPipe2) => GenericOutputPipe3, pipe4: (input: GenericOutputPipe3) => GenericOutputPipe4): BreakGenericLink<GenericOutputPipe4>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2, pipe3: (input: GenericOutputPipe2) => GenericOutputPipe3, pipe4: (input: GenericOutputPipe3) => GenericOutputPipe4, pipe5: (input: GenericOutputPipe4) => GenericOutputPipe5): BreakGenericLink<GenericOutputPipe5>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2, pipe3: (input: GenericOutputPipe2) => GenericOutputPipe3, pipe4: (input: GenericOutputPipe3) => GenericOutputPipe4, pipe5: (input: GenericOutputPipe4) => GenericOutputPipe5, pipe6: (input: GenericOutputPipe5) => GenericOutputPipe6): BreakGenericLink<GenericOutputPipe6>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2, pipe3: (input: GenericOutputPipe2) => GenericOutputPipe3, pipe4: (input: GenericOutputPipe3) => GenericOutputPipe4, pipe5: (input: GenericOutputPipe4) => GenericOutputPipe5, pipe6: (input: GenericOutputPipe5) => GenericOutputPipe6, pipe7: (input: GenericOutputPipe6) => GenericOutputPipe7): BreakGenericLink<GenericOutputPipe7>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2, pipe3: (input: GenericOutputPipe2) => GenericOutputPipe3, pipe4: (input: GenericOutputPipe3) => GenericOutputPipe4, pipe5: (input: GenericOutputPipe4) => GenericOutputPipe5, pipe6: (input: GenericOutputPipe5) => GenericOutputPipe6, pipe7: (input: GenericOutputPipe6) => GenericOutputPipe7, pipe8: (input: GenericOutputPipe7) => GenericOutputPipe8): BreakGenericLink<GenericOutputPipe8>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2, pipe3: (input: GenericOutputPipe2) => GenericOutputPipe3, pipe4: (input: GenericOutputPipe3) => GenericOutputPipe4, pipe5: (input: GenericOutputPipe4) => GenericOutputPipe5, pipe6: (input: GenericOutputPipe5) => GenericOutputPipe6, pipe7: (input: GenericOutputPipe6) => GenericOutputPipe7, pipe8: (input: GenericOutputPipe7) => GenericOutputPipe8, pipe9: (input: GenericOutputPipe8) => GenericOutputPipe9): BreakGenericLink<GenericOutputPipe9>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2, pipe3: (input: GenericOutputPipe2) => GenericOutputPipe3, pipe4: (input: GenericOutputPipe3) => GenericOutputPipe4, pipe5: (input: GenericOutputPipe4) => GenericOutputPipe5, pipe6: (input: GenericOutputPipe5) => GenericOutputPipe6, pipe7: (input: GenericOutputPipe6) => GenericOutputPipe7, pipe8: (input: GenericOutputPipe7) => GenericOutputPipe8, pipe9: (input: GenericOutputPipe8) => GenericOutputPipe9, pipe10: (input: GenericOutputPipe9) => GenericOutputPipe10): BreakGenericLink<GenericOutputPipe10>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2, pipe3: (input: GenericOutputPipe2) => GenericOutputPipe3, pipe4: (input: GenericOutputPipe3) => GenericOutputPipe4, pipe5: (input: GenericOutputPipe4) => GenericOutputPipe5, pipe6: (input: GenericOutputPipe5) => GenericOutputPipe6, pipe7: (input: GenericOutputPipe6) => GenericOutputPipe7, pipe8: (input: GenericOutputPipe7) => GenericOutputPipe8, pipe9: (input: GenericOutputPipe8) => GenericOutputPipe9, pipe10: (input: GenericOutputPipe9) => GenericOutputPipe10, pipe11: (input: GenericOutputPipe10) => GenericOutputPipe11): BreakGenericLink<GenericOutputPipe11>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown, const GenericOutputPipe12 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2, pipe3: (input: GenericOutputPipe2) => GenericOutputPipe3, pipe4: (input: GenericOutputPipe3) => GenericOutputPipe4, pipe5: (input: GenericOutputPipe4) => GenericOutputPipe5, pipe6: (input: GenericOutputPipe5) => GenericOutputPipe6, pipe7: (input: GenericOutputPipe6) => GenericOutputPipe7, pipe8: (input: GenericOutputPipe7) => GenericOutputPipe8, pipe9: (input: GenericOutputPipe8) => GenericOutputPipe9, pipe10: (input: GenericOutputPipe9) => GenericOutputPipe10, pipe11: (input: GenericOutputPipe10) => GenericOutputPipe11, pipe12: (input: GenericOutputPipe11) => GenericOutputPipe12): BreakGenericLink<GenericOutputPipe12>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown, const GenericOutputPipe12 extends unknown, const GenericOutputPipe13 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2, pipe3: (input: GenericOutputPipe2) => GenericOutputPipe3, pipe4: (input: GenericOutputPipe3) => GenericOutputPipe4, pipe5: (input: GenericOutputPipe4) => GenericOutputPipe5, pipe6: (input: GenericOutputPipe5) => GenericOutputPipe6, pipe7: (input: GenericOutputPipe6) => GenericOutputPipe7, pipe8: (input: GenericOutputPipe7) => GenericOutputPipe8, pipe9: (input: GenericOutputPipe8) => GenericOutputPipe9, pipe10: (input: GenericOutputPipe9) => GenericOutputPipe10, pipe11: (input: GenericOutputPipe10) => GenericOutputPipe11, pipe12: (input: GenericOutputPipe11) => GenericOutputPipe12, pipe13: (input: GenericOutputPipe12) => GenericOutputPipe13): BreakGenericLink<GenericOutputPipe13>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown, const GenericOutputPipe12 extends unknown, const GenericOutputPipe13 extends unknown, const GenericOutputPipe14 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2, pipe3: (input: GenericOutputPipe2) => GenericOutputPipe3, pipe4: (input: GenericOutputPipe3) => GenericOutputPipe4, pipe5: (input: GenericOutputPipe4) => GenericOutputPipe5, pipe6: (input: GenericOutputPipe5) => GenericOutputPipe6, pipe7: (input: GenericOutputPipe6) => GenericOutputPipe7, pipe8: (input: GenericOutputPipe7) => GenericOutputPipe8, pipe9: (input: GenericOutputPipe8) => GenericOutputPipe9, pipe10: (input: GenericOutputPipe9) => GenericOutputPipe10, pipe11: (input: GenericOutputPipe10) => GenericOutputPipe11, pipe12: (input: GenericOutputPipe11) => GenericOutputPipe12, pipe13: (input: GenericOutputPipe12) => GenericOutputPipe13, pipe14: (input: GenericOutputPipe13) => GenericOutputPipe14): BreakGenericLink<GenericOutputPipe14>;
export declare function pipe<const GenericInput extends unknown, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown, const GenericOutputPipe12 extends unknown, const GenericOutputPipe13 extends unknown, const GenericOutputPipe14 extends unknown, const GenericOutputPipe15 extends unknown>(input: GenericInput, pipe1: (input: GenericInput) => GenericOutputPipe1, pipe2: (input: GenericOutputPipe1) => GenericOutputPipe2, pipe3: (input: GenericOutputPipe2) => GenericOutputPipe3, pipe4: (input: GenericOutputPipe3) => GenericOutputPipe4, pipe5: (input: GenericOutputPipe4) => GenericOutputPipe5, pipe6: (input: GenericOutputPipe5) => GenericOutputPipe6, pipe7: (input: GenericOutputPipe6) => GenericOutputPipe7, pipe8: (input: GenericOutputPipe7) => GenericOutputPipe8, pipe9: (input: GenericOutputPipe8) => GenericOutputPipe9, pipe10: (input: GenericOutputPipe9) => GenericOutputPipe10, pipe11: (input: GenericOutputPipe10) => GenericOutputPipe11, pipe12: (input: GenericOutputPipe11) => GenericOutputPipe12, pipe13: (input: GenericOutputPipe12) => GenericOutputPipe13, pipe14: (input: GenericOutputPipe13) => GenericOutputPipe14, pipe15: (input: GenericOutputPipe14) => GenericOutputPipe15): BreakGenericLink<GenericOutputPipe15>;
