import { type BreakGenericLink, type MaybePromise } from "./types";
export interface PrepareAsyncPipe<GenericInput extends unknown = undefined> {
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe1>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe2>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2, pipe3: (input: Awaited<GenericOutputPipe2>) => GenericOutputPipe3): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe3>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2, pipe3: (input: Awaited<GenericOutputPipe2>) => GenericOutputPipe3, pipe4: (input: Awaited<GenericOutputPipe3>) => GenericOutputPipe4): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe4>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2, pipe3: (input: Awaited<GenericOutputPipe2>) => GenericOutputPipe3, pipe4: (input: Awaited<GenericOutputPipe3>) => GenericOutputPipe4, pipe5: (input: Awaited<GenericOutputPipe4>) => GenericOutputPipe5): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe5>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2, pipe3: (input: Awaited<GenericOutputPipe2>) => GenericOutputPipe3, pipe4: (input: Awaited<GenericOutputPipe3>) => GenericOutputPipe4, pipe5: (input: Awaited<GenericOutputPipe4>) => GenericOutputPipe5, pipe6: (input: Awaited<GenericOutputPipe5>) => GenericOutputPipe6): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe6>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2, pipe3: (input: Awaited<GenericOutputPipe2>) => GenericOutputPipe3, pipe4: (input: Awaited<GenericOutputPipe3>) => GenericOutputPipe4, pipe5: (input: Awaited<GenericOutputPipe4>) => GenericOutputPipe5, pipe6: (input: Awaited<GenericOutputPipe5>) => GenericOutputPipe6, pipe7: (input: Awaited<GenericOutputPipe6>) => GenericOutputPipe7): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe7>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2, pipe3: (input: Awaited<GenericOutputPipe2>) => GenericOutputPipe3, pipe4: (input: Awaited<GenericOutputPipe3>) => GenericOutputPipe4, pipe5: (input: Awaited<GenericOutputPipe4>) => GenericOutputPipe5, pipe6: (input: Awaited<GenericOutputPipe5>) => GenericOutputPipe6, pipe7: (input: Awaited<GenericOutputPipe6>) => GenericOutputPipe7, pipe8: (input: Awaited<GenericOutputPipe7>) => GenericOutputPipe8): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe8>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2, pipe3: (input: Awaited<GenericOutputPipe2>) => GenericOutputPipe3, pipe4: (input: Awaited<GenericOutputPipe3>) => GenericOutputPipe4, pipe5: (input: Awaited<GenericOutputPipe4>) => GenericOutputPipe5, pipe6: (input: Awaited<GenericOutputPipe5>) => GenericOutputPipe6, pipe7: (input: Awaited<GenericOutputPipe6>) => GenericOutputPipe7, pipe8: (input: Awaited<GenericOutputPipe7>) => GenericOutputPipe8, pipe9: (input: Awaited<GenericOutputPipe8>) => GenericOutputPipe9): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe9>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2, pipe3: (input: Awaited<GenericOutputPipe2>) => GenericOutputPipe3, pipe4: (input: Awaited<GenericOutputPipe3>) => GenericOutputPipe4, pipe5: (input: Awaited<GenericOutputPipe4>) => GenericOutputPipe5, pipe6: (input: Awaited<GenericOutputPipe5>) => GenericOutputPipe6, pipe7: (input: Awaited<GenericOutputPipe6>) => GenericOutputPipe7, pipe8: (input: Awaited<GenericOutputPipe7>) => GenericOutputPipe8, pipe9: (input: Awaited<GenericOutputPipe8>) => GenericOutputPipe9, pipe10: (input: Awaited<GenericOutputPipe9>) => GenericOutputPipe10): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe10>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2, pipe3: (input: Awaited<GenericOutputPipe2>) => GenericOutputPipe3, pipe4: (input: Awaited<GenericOutputPipe3>) => GenericOutputPipe4, pipe5: (input: Awaited<GenericOutputPipe4>) => GenericOutputPipe5, pipe6: (input: Awaited<GenericOutputPipe5>) => GenericOutputPipe6, pipe7: (input: Awaited<GenericOutputPipe6>) => GenericOutputPipe7, pipe8: (input: Awaited<GenericOutputPipe7>) => GenericOutputPipe8, pipe9: (input: Awaited<GenericOutputPipe8>) => GenericOutputPipe9, pipe10: (input: Awaited<GenericOutputPipe9>) => GenericOutputPipe10, pipe11: (input: Awaited<GenericOutputPipe10>) => GenericOutputPipe11): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe11>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown, const GenericOutputPipe12 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2, pipe3: (input: Awaited<GenericOutputPipe2>) => GenericOutputPipe3, pipe4: (input: Awaited<GenericOutputPipe3>) => GenericOutputPipe4, pipe5: (input: Awaited<GenericOutputPipe4>) => GenericOutputPipe5, pipe6: (input: Awaited<GenericOutputPipe5>) => GenericOutputPipe6, pipe7: (input: Awaited<GenericOutputPipe6>) => GenericOutputPipe7, pipe8: (input: Awaited<GenericOutputPipe7>) => GenericOutputPipe8, pipe9: (input: Awaited<GenericOutputPipe8>) => GenericOutputPipe9, pipe10: (input: Awaited<GenericOutputPipe9>) => GenericOutputPipe10, pipe11: (input: Awaited<GenericOutputPipe10>) => GenericOutputPipe11, pipe12: (input: Awaited<GenericOutputPipe11>) => GenericOutputPipe12): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe12>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown, const GenericOutputPipe12 extends unknown, const GenericOutputPipe13 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2, pipe3: (input: Awaited<GenericOutputPipe2>) => GenericOutputPipe3, pipe4: (input: Awaited<GenericOutputPipe3>) => GenericOutputPipe4, pipe5: (input: Awaited<GenericOutputPipe4>) => GenericOutputPipe5, pipe6: (input: Awaited<GenericOutputPipe5>) => GenericOutputPipe6, pipe7: (input: Awaited<GenericOutputPipe6>) => GenericOutputPipe7, pipe8: (input: Awaited<GenericOutputPipe7>) => GenericOutputPipe8, pipe9: (input: Awaited<GenericOutputPipe8>) => GenericOutputPipe9, pipe10: (input: Awaited<GenericOutputPipe9>) => GenericOutputPipe10, pipe11: (input: Awaited<GenericOutputPipe10>) => GenericOutputPipe11, pipe12: (input: Awaited<GenericOutputPipe11>) => GenericOutputPipe12, pipe13: (input: Awaited<GenericOutputPipe12>) => GenericOutputPipe13): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe13>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown, const GenericOutputPipe12 extends unknown, const GenericOutputPipe13 extends unknown, const GenericOutputPipe14 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2, pipe3: (input: Awaited<GenericOutputPipe2>) => GenericOutputPipe3, pipe4: (input: Awaited<GenericOutputPipe3>) => GenericOutputPipe4, pipe5: (input: Awaited<GenericOutputPipe4>) => GenericOutputPipe5, pipe6: (input: Awaited<GenericOutputPipe5>) => GenericOutputPipe6, pipe7: (input: Awaited<GenericOutputPipe6>) => GenericOutputPipe7, pipe8: (input: Awaited<GenericOutputPipe7>) => GenericOutputPipe8, pipe9: (input: Awaited<GenericOutputPipe8>) => GenericOutputPipe9, pipe10: (input: Awaited<GenericOutputPipe9>) => GenericOutputPipe10, pipe11: (input: Awaited<GenericOutputPipe10>) => GenericOutputPipe11, pipe12: (input: Awaited<GenericOutputPipe11>) => GenericOutputPipe12, pipe13: (input: Awaited<GenericOutputPipe12>) => GenericOutputPipe13, pipe14: (input: Awaited<GenericOutputPipe13>) => GenericOutputPipe14): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe14>>;
    <const GenericLocalInput extends GenericInput, const GenericOutputPipe1 extends unknown, const GenericOutputPipe2 extends unknown, const GenericOutputPipe3 extends unknown, const GenericOutputPipe4 extends unknown, const GenericOutputPipe5 extends unknown, const GenericOutputPipe6 extends unknown, const GenericOutputPipe7 extends unknown, const GenericOutputPipe8 extends unknown, const GenericOutputPipe9 extends unknown, const GenericOutputPipe10 extends unknown, const GenericOutputPipe11 extends unknown, const GenericOutputPipe12 extends unknown, const GenericOutputPipe13 extends unknown, const GenericOutputPipe14 extends unknown, const GenericOutputPipe15 extends unknown>(pipe1: (input: BreakGenericLink<Awaited<GenericLocalInput>>) => GenericOutputPipe1, pipe2: (input: Awaited<GenericOutputPipe1>) => GenericOutputPipe2, pipe3: (input: Awaited<GenericOutputPipe2>) => GenericOutputPipe3, pipe4: (input: Awaited<GenericOutputPipe3>) => GenericOutputPipe4, pipe5: (input: Awaited<GenericOutputPipe4>) => GenericOutputPipe5, pipe6: (input: Awaited<GenericOutputPipe5>) => GenericOutputPipe6, pipe7: (input: Awaited<GenericOutputPipe6>) => GenericOutputPipe7, pipe8: (input: Awaited<GenericOutputPipe7>) => GenericOutputPipe8, pipe9: (input: Awaited<GenericOutputPipe8>) => GenericOutputPipe9, pipe10: (input: Awaited<GenericOutputPipe9>) => GenericOutputPipe10, pipe11: (input: Awaited<GenericOutputPipe10>) => GenericOutputPipe11, pipe12: (input: Awaited<GenericOutputPipe11>) => GenericOutputPipe12, pipe13: (input: Awaited<GenericOutputPipe12>) => GenericOutputPipe13, pipe14: (input: Awaited<GenericOutputPipe13>) => GenericOutputPipe14, pipe15: (input: Awaited<GenericOutputPipe14>) => GenericOutputPipe15): (input: MaybePromise<GenericLocalInput>) => Promise<Awaited<GenericOutputPipe15>>;
}
/** Prepares a reusable asynchronous pipeline whose steps are declared once and whose input type can be inferred from the resulting function's context.
/** 
/** **Supported call styles:**
/** - Explicit input: `prepareAsyncPipe<Input>()(pipe1, pipe2)` -> returns a typed reusable async function
/** - Contextual input: `const fn: (input: Input) => Promise<Output> = prepareAsyncPipe()(pipe1, pipe2)` -> infers the local input from the target function type
/** 
/** Each step may return a direct value or a promise. Every execution accepts a direct input or a promise, awaits the prepared sequence, and returns a promise of the final output.
/** 
/** ```ts
/** const fetchLabel = prepareAsyncPipe<number>()(
/** 	async(value) => Promise.resolve(value * 2),
/** 	S.to,
/** );
/** 
/** await fetchLabel(10); // "20"
/** await fetchLabel(Promise.resolve(15)); // "30"
/** 
/** const numberToString: (
/** 	input: number
/** ) => Promise<string> = prepareAsyncPipe()(
/** 	S.to,
/** );
/** 
/** await numberToString(42); // "42"
/** 
/** const normalizeName = prepareAsyncPipe<string>()(
/** 	async(value) => Promise.resolve(value.trim()),
/** 	(value) => value.toUpperCase(),
/** );
/** 
/** await pipe(
/** 	"  Ada  ",
/** 	normalizeName,
/** ); // "ADA"
/** ```
/** 
/** @remarks Contextual input inference is useful when declaring recursive or mutually recursive async functions because the complete input-to-output contract can be written before the pipeline is built.
/** 
/** @see https://utils.duplojs.dev/en/v1/api/common/prepareAsyncPipe
/** @see [`asyncInnerPipe`](https://utils.duplojs.dev/en/v1/api/common/asyncInnerPipe)
/**  */
export declare function prepareAsyncPipe<GenericInput extends unknown = unknown>(): PrepareAsyncPipe<GenericInput>;
