import { type Right } from "./create";
import { type Left } from "../left";
import { type Success } from "./success";
import { type AnyValue, type Unwrap } from "../../common";
type Either = Right | Left;
export type RightPipeFunction<GenericInput extends AnyValue = AnyValue, GenericOutput extends AnyValue = AnyValue> = (input: GenericInput extends Either ? Unwrap<Exclude<GenericInput, Left>> : GenericInput) => GenericOutput;
/**
 * @deprecated use RightPipeFunction
 */
export type EitherRightPipeFunction<GenericInput extends AnyValue = AnyValue, GenericOutput extends AnyValue = AnyValue> = RightPipeFunction<GenericInput, GenericOutput>;
export type RightPipeResult<GenericPipeOutputs extends AnyValue, GenericLastPipeOutput extends AnyValue> = Extract<GenericPipeOutputs, Left> | Exclude<GenericLastPipeOutput extends Either ? GenericLastPipeOutput : Success<GenericLastPipeOutput>, Left>;
/**
 * @deprecated use RightPipeResult
 */
export type EitherRightPipeResult<GenericPipeOutputs extends AnyValue, GenericLastPipeOutput extends AnyValue> = RightPipeResult<GenericPipeOutputs, GenericLastPipeOutput>;
/**
 * Chains synchronous transformations on an Either as long as it remains Right. The pipeline stops as soon as a Left is returned.
 * 
 * Signature: `rightPipe(input, pipe1, pipe2)` → returns a value
 * 
 * The input value is not mutated.
 * 
 * ```ts
 * import { E } from "../..";
 * 
 * const input: (
 * 	| E.Fail
 * 	| E.NullableEmpty
 * 	| E.Right<"right", 1>
 * ) = E.right("right", 1);
 * 
 * const result = E.rightPipe(
 * 	input,
 * 	(value) => {
 * 		// type: 1 | 2
 * 		return value;
 * 	},
 * );
 * ```
 * 
 * @remarks
 * - Stops at the first Left and forwards it as-is.
 * 
 * @see https://utils.duplojs.dev/en/v1/api/either/rightPipe
 * 
 * @namespace E
 * 
 */
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1, GenericOutputPipe1>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2, GenericOutputPipe2>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue, GenericOutputPipe3 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>, pipe3: RightPipeFunction<GenericOutputPipe2, GenericOutputPipe3>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2 | GenericOutputPipe3, GenericOutputPipe3>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue, GenericOutputPipe3 extends AnyValue, GenericOutputPipe4 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>, pipe3: RightPipeFunction<GenericOutputPipe2, GenericOutputPipe3>, pipe4: RightPipeFunction<GenericOutputPipe3, GenericOutputPipe4>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2 | GenericOutputPipe3 | GenericOutputPipe4, GenericOutputPipe4>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue, GenericOutputPipe3 extends AnyValue, GenericOutputPipe4 extends AnyValue, GenericOutputPipe5 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>, pipe3: RightPipeFunction<GenericOutputPipe2, GenericOutputPipe3>, pipe4: RightPipeFunction<GenericOutputPipe3, GenericOutputPipe4>, pipe5: RightPipeFunction<GenericOutputPipe4, GenericOutputPipe5>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2 | GenericOutputPipe3 | GenericOutputPipe4 | GenericOutputPipe5, GenericOutputPipe5>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue, GenericOutputPipe3 extends AnyValue, GenericOutputPipe4 extends AnyValue, GenericOutputPipe5 extends AnyValue, GenericOutputPipe6 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>, pipe3: RightPipeFunction<GenericOutputPipe2, GenericOutputPipe3>, pipe4: RightPipeFunction<GenericOutputPipe3, GenericOutputPipe4>, pipe5: RightPipeFunction<GenericOutputPipe4, GenericOutputPipe5>, pipe6: RightPipeFunction<GenericOutputPipe5, GenericOutputPipe6>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2 | GenericOutputPipe3 | GenericOutputPipe4 | GenericOutputPipe5 | GenericOutputPipe6, GenericOutputPipe6>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue, GenericOutputPipe3 extends AnyValue, GenericOutputPipe4 extends AnyValue, GenericOutputPipe5 extends AnyValue, GenericOutputPipe6 extends AnyValue, GenericOutputPipe7 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>, pipe3: RightPipeFunction<GenericOutputPipe2, GenericOutputPipe3>, pipe4: RightPipeFunction<GenericOutputPipe3, GenericOutputPipe4>, pipe5: RightPipeFunction<GenericOutputPipe4, GenericOutputPipe5>, pipe6: RightPipeFunction<GenericOutputPipe5, GenericOutputPipe6>, pipe7: RightPipeFunction<GenericOutputPipe6, GenericOutputPipe7>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2 | GenericOutputPipe3 | GenericOutputPipe4 | GenericOutputPipe5 | GenericOutputPipe6 | GenericOutputPipe7, GenericOutputPipe7>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue, GenericOutputPipe3 extends AnyValue, GenericOutputPipe4 extends AnyValue, GenericOutputPipe5 extends AnyValue, GenericOutputPipe6 extends AnyValue, GenericOutputPipe7 extends AnyValue, GenericOutputPipe8 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>, pipe3: RightPipeFunction<GenericOutputPipe2, GenericOutputPipe3>, pipe4: RightPipeFunction<GenericOutputPipe3, GenericOutputPipe4>, pipe5: RightPipeFunction<GenericOutputPipe4, GenericOutputPipe5>, pipe6: RightPipeFunction<GenericOutputPipe5, GenericOutputPipe6>, pipe7: RightPipeFunction<GenericOutputPipe6, GenericOutputPipe7>, pipe8: RightPipeFunction<GenericOutputPipe7, GenericOutputPipe8>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2 | GenericOutputPipe3 | GenericOutputPipe4 | GenericOutputPipe5 | GenericOutputPipe6 | GenericOutputPipe7 | GenericOutputPipe8, GenericOutputPipe8>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue, GenericOutputPipe3 extends AnyValue, GenericOutputPipe4 extends AnyValue, GenericOutputPipe5 extends AnyValue, GenericOutputPipe6 extends AnyValue, GenericOutputPipe7 extends AnyValue, GenericOutputPipe8 extends AnyValue, GenericOutputPipe9 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>, pipe3: RightPipeFunction<GenericOutputPipe2, GenericOutputPipe3>, pipe4: RightPipeFunction<GenericOutputPipe3, GenericOutputPipe4>, pipe5: RightPipeFunction<GenericOutputPipe4, GenericOutputPipe5>, pipe6: RightPipeFunction<GenericOutputPipe5, GenericOutputPipe6>, pipe7: RightPipeFunction<GenericOutputPipe6, GenericOutputPipe7>, pipe8: RightPipeFunction<GenericOutputPipe7, GenericOutputPipe8>, pipe9: RightPipeFunction<GenericOutputPipe8, GenericOutputPipe9>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2 | GenericOutputPipe3 | GenericOutputPipe4 | GenericOutputPipe5 | GenericOutputPipe6 | GenericOutputPipe7 | GenericOutputPipe8 | GenericOutputPipe9, GenericOutputPipe9>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue, GenericOutputPipe3 extends AnyValue, GenericOutputPipe4 extends AnyValue, GenericOutputPipe5 extends AnyValue, GenericOutputPipe6 extends AnyValue, GenericOutputPipe7 extends AnyValue, GenericOutputPipe8 extends AnyValue, GenericOutputPipe9 extends AnyValue, GenericOutputPipe10 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>, pipe3: RightPipeFunction<GenericOutputPipe2, GenericOutputPipe3>, pipe4: RightPipeFunction<GenericOutputPipe3, GenericOutputPipe4>, pipe5: RightPipeFunction<GenericOutputPipe4, GenericOutputPipe5>, pipe6: RightPipeFunction<GenericOutputPipe5, GenericOutputPipe6>, pipe7: RightPipeFunction<GenericOutputPipe6, GenericOutputPipe7>, pipe8: RightPipeFunction<GenericOutputPipe7, GenericOutputPipe8>, pipe9: RightPipeFunction<GenericOutputPipe8, GenericOutputPipe9>, pipe10: RightPipeFunction<GenericOutputPipe9, GenericOutputPipe10>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2 | GenericOutputPipe3 | GenericOutputPipe4 | GenericOutputPipe5 | GenericOutputPipe6 | GenericOutputPipe7 | GenericOutputPipe8 | GenericOutputPipe9 | GenericOutputPipe10, GenericOutputPipe10>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue, GenericOutputPipe3 extends AnyValue, GenericOutputPipe4 extends AnyValue, GenericOutputPipe5 extends AnyValue, GenericOutputPipe6 extends AnyValue, GenericOutputPipe7 extends AnyValue, GenericOutputPipe8 extends AnyValue, GenericOutputPipe9 extends AnyValue, GenericOutputPipe10 extends AnyValue, GenericOutputPipe11 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>, pipe3: RightPipeFunction<GenericOutputPipe2, GenericOutputPipe3>, pipe4: RightPipeFunction<GenericOutputPipe3, GenericOutputPipe4>, pipe5: RightPipeFunction<GenericOutputPipe4, GenericOutputPipe5>, pipe6: RightPipeFunction<GenericOutputPipe5, GenericOutputPipe6>, pipe7: RightPipeFunction<GenericOutputPipe6, GenericOutputPipe7>, pipe8: RightPipeFunction<GenericOutputPipe7, GenericOutputPipe8>, pipe9: RightPipeFunction<GenericOutputPipe8, GenericOutputPipe9>, pipe10: RightPipeFunction<GenericOutputPipe9, GenericOutputPipe10>, pipe11: RightPipeFunction<GenericOutputPipe10, GenericOutputPipe11>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2 | GenericOutputPipe3 | GenericOutputPipe4 | GenericOutputPipe5 | GenericOutputPipe6 | GenericOutputPipe7 | GenericOutputPipe8 | GenericOutputPipe9 | GenericOutputPipe10 | GenericOutputPipe11, GenericOutputPipe11>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue, GenericOutputPipe3 extends AnyValue, GenericOutputPipe4 extends AnyValue, GenericOutputPipe5 extends AnyValue, GenericOutputPipe6 extends AnyValue, GenericOutputPipe7 extends AnyValue, GenericOutputPipe8 extends AnyValue, GenericOutputPipe9 extends AnyValue, GenericOutputPipe10 extends AnyValue, GenericOutputPipe11 extends AnyValue, GenericOutputPipe12 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>, pipe3: RightPipeFunction<GenericOutputPipe2, GenericOutputPipe3>, pipe4: RightPipeFunction<GenericOutputPipe3, GenericOutputPipe4>, pipe5: RightPipeFunction<GenericOutputPipe4, GenericOutputPipe5>, pipe6: RightPipeFunction<GenericOutputPipe5, GenericOutputPipe6>, pipe7: RightPipeFunction<GenericOutputPipe6, GenericOutputPipe7>, pipe8: RightPipeFunction<GenericOutputPipe7, GenericOutputPipe8>, pipe9: RightPipeFunction<GenericOutputPipe8, GenericOutputPipe9>, pipe10: RightPipeFunction<GenericOutputPipe9, GenericOutputPipe10>, pipe11: RightPipeFunction<GenericOutputPipe10, GenericOutputPipe11>, pipe12: RightPipeFunction<GenericOutputPipe11, GenericOutputPipe12>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2 | GenericOutputPipe3 | GenericOutputPipe4 | GenericOutputPipe5 | GenericOutputPipe6 | GenericOutputPipe7 | GenericOutputPipe8 | GenericOutputPipe9 | GenericOutputPipe10 | GenericOutputPipe11 | GenericOutputPipe12, GenericOutputPipe12>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue, GenericOutputPipe3 extends AnyValue, GenericOutputPipe4 extends AnyValue, GenericOutputPipe5 extends AnyValue, GenericOutputPipe6 extends AnyValue, GenericOutputPipe7 extends AnyValue, GenericOutputPipe8 extends AnyValue, GenericOutputPipe9 extends AnyValue, GenericOutputPipe10 extends AnyValue, GenericOutputPipe11 extends AnyValue, GenericOutputPipe12 extends AnyValue, GenericOutputPipe13 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>, pipe3: RightPipeFunction<GenericOutputPipe2, GenericOutputPipe3>, pipe4: RightPipeFunction<GenericOutputPipe3, GenericOutputPipe4>, pipe5: RightPipeFunction<GenericOutputPipe4, GenericOutputPipe5>, pipe6: RightPipeFunction<GenericOutputPipe5, GenericOutputPipe6>, pipe7: RightPipeFunction<GenericOutputPipe6, GenericOutputPipe7>, pipe8: RightPipeFunction<GenericOutputPipe7, GenericOutputPipe8>, pipe9: RightPipeFunction<GenericOutputPipe8, GenericOutputPipe9>, pipe10: RightPipeFunction<GenericOutputPipe9, GenericOutputPipe10>, pipe11: RightPipeFunction<GenericOutputPipe10, GenericOutputPipe11>, pipe12: RightPipeFunction<GenericOutputPipe11, GenericOutputPipe12>, pipe13: RightPipeFunction<GenericOutputPipe12, GenericOutputPipe13>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2 | GenericOutputPipe3 | GenericOutputPipe4 | GenericOutputPipe5 | GenericOutputPipe6 | GenericOutputPipe7 | GenericOutputPipe8 | GenericOutputPipe9 | GenericOutputPipe10 | GenericOutputPipe11 | GenericOutputPipe12 | GenericOutputPipe13, GenericOutputPipe13>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue, GenericOutputPipe3 extends AnyValue, GenericOutputPipe4 extends AnyValue, GenericOutputPipe5 extends AnyValue, GenericOutputPipe6 extends AnyValue, GenericOutputPipe7 extends AnyValue, GenericOutputPipe8 extends AnyValue, GenericOutputPipe9 extends AnyValue, GenericOutputPipe10 extends AnyValue, GenericOutputPipe11 extends AnyValue, GenericOutputPipe12 extends AnyValue, GenericOutputPipe13 extends AnyValue, GenericOutputPipe14 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>, pipe3: RightPipeFunction<GenericOutputPipe2, GenericOutputPipe3>, pipe4: RightPipeFunction<GenericOutputPipe3, GenericOutputPipe4>, pipe5: RightPipeFunction<GenericOutputPipe4, GenericOutputPipe5>, pipe6: RightPipeFunction<GenericOutputPipe5, GenericOutputPipe6>, pipe7: RightPipeFunction<GenericOutputPipe6, GenericOutputPipe7>, pipe8: RightPipeFunction<GenericOutputPipe7, GenericOutputPipe8>, pipe9: RightPipeFunction<GenericOutputPipe8, GenericOutputPipe9>, pipe10: RightPipeFunction<GenericOutputPipe9, GenericOutputPipe10>, pipe11: RightPipeFunction<GenericOutputPipe10, GenericOutputPipe11>, pipe12: RightPipeFunction<GenericOutputPipe11, GenericOutputPipe12>, pipe13: RightPipeFunction<GenericOutputPipe12, GenericOutputPipe13>, pipe14: RightPipeFunction<GenericOutputPipe13, GenericOutputPipe14>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2 | GenericOutputPipe3 | GenericOutputPipe4 | GenericOutputPipe5 | GenericOutputPipe6 | GenericOutputPipe7 | GenericOutputPipe8 | GenericOutputPipe9 | GenericOutputPipe10 | GenericOutputPipe11 | GenericOutputPipe12 | GenericOutputPipe13 | GenericOutputPipe14, GenericOutputPipe14>, any>;
export declare function rightPipe<GenericInput extends AnyValue, GenericOutputPipe1 extends AnyValue, GenericOutputPipe2 extends AnyValue, GenericOutputPipe3 extends AnyValue, GenericOutputPipe4 extends AnyValue, GenericOutputPipe5 extends AnyValue, GenericOutputPipe6 extends AnyValue, GenericOutputPipe7 extends AnyValue, GenericOutputPipe8 extends AnyValue, GenericOutputPipe9 extends AnyValue, GenericOutputPipe10 extends AnyValue, GenericOutputPipe11 extends AnyValue, GenericOutputPipe12 extends AnyValue, GenericOutputPipe13 extends AnyValue, GenericOutputPipe14 extends AnyValue, GenericOutputPipe15 extends AnyValue>(input: GenericInput, pipe1: RightPipeFunction<GenericInput, GenericOutputPipe1>, pipe2: RightPipeFunction<GenericOutputPipe1, GenericOutputPipe2>, pipe3: RightPipeFunction<GenericOutputPipe2, GenericOutputPipe3>, pipe4: RightPipeFunction<GenericOutputPipe3, GenericOutputPipe4>, pipe5: RightPipeFunction<GenericOutputPipe4, GenericOutputPipe5>, pipe6: RightPipeFunction<GenericOutputPipe5, GenericOutputPipe6>, pipe7: RightPipeFunction<GenericOutputPipe6, GenericOutputPipe7>, pipe8: RightPipeFunction<GenericOutputPipe7, GenericOutputPipe8>, pipe9: RightPipeFunction<GenericOutputPipe8, GenericOutputPipe9>, pipe10: RightPipeFunction<GenericOutputPipe9, GenericOutputPipe10>, pipe11: RightPipeFunction<GenericOutputPipe10, GenericOutputPipe11>, pipe12: RightPipeFunction<GenericOutputPipe11, GenericOutputPipe12>, pipe13: RightPipeFunction<GenericOutputPipe12, GenericOutputPipe13>, pipe14: RightPipeFunction<GenericOutputPipe13, GenericOutputPipe14>, pipe15: RightPipeFunction<GenericOutputPipe14, GenericOutputPipe15>): Extract<RightPipeResult<GenericInput | GenericOutputPipe1 | GenericOutputPipe2 | GenericOutputPipe3 | GenericOutputPipe4 | GenericOutputPipe5 | GenericOutputPipe6 | GenericOutputPipe7 | GenericOutputPipe8 | GenericOutputPipe9 | GenericOutputPipe10 | GenericOutputPipe11 | GenericOutputPipe12 | GenericOutputPipe13 | GenericOutputPipe14 | GenericOutputPipe15, GenericOutputPipe15>, any>;
export {};
